[INFO]2021-06-03 12:57:25,329: log files at C:\Users\comba\Desktop\KLC\knowledgeCity\common\log
[INFO]2021-06-03 12:57:25,329: find module agvCtrl.main_agv
[INFO]2021-06-03 12:57:25,330: find module agvDevice.main_agvDevice
[INFO]2021-06-03 12:57:25,330: find module alarm.main_alarm
[INFO]2021-06-03 12:57:25,330: find module auth.main_auth
[INFO]2021-06-03 12:57:25,331: find module autoCtrl.main_akmCtrl
[INFO]2021-06-03 12:57:25,331: find module door.main_door
[INFO]2021-06-03 12:57:25,331: find module elevator.main_elevator
[INFO]2021-06-03 12:57:25,332: find module feed.main_feed
[INFO]2021-06-03 12:57:25,337: find module remoteio.main_remoteio
[INFO]2021-06-03 12:57:25,338: import agvCtrl.main_agv
[INFO]2021-06-03 12:57:25,566: create lock <lock name:doorMgr.lock,<unlocked _thread.RLock object owner=0 count=0 at 0x00000276619847B0>>
[INFO]2021-06-03 12:57:25,567: create lock <lock name:door.lock,<unlocked _thread.RLock object owner=0 count=0 at 0x0000027661984918>>
[INFO]2021-06-03 12:57:25,614: create lock <lock name:timer.lock_2707469212192,<unlocked _thread.RLock object owner=0 count=0 at 0x0000027661BCF440>>
[ERROR]2021-06-03 12:57:25,620: mqtt is disabled
[INFO]2021-06-03 12:57:25,621: mqtt: subscribe [alarm/raise/+]
[INFO]2021-06-03 12:57:25,621: mqtt: subscribe [alarm/clear/+]
[INFO]2021-06-03 12:57:28,640: Mongodb connect to 127.0.0.1 port 27017
[INFO]2021-06-03 12:57:28,682: create lock <lock name:elevatorApi.tcp_lock,<unlocked _thread.RLock object owner=0 count=0 at 0x0000027661D98B48>>
[INFO]2021-06-03 12:57:28,684: create lock <lock name:elevatorApi.g_lock,<unlocked _thread.RLock object owner=0 count=0 at 0x0000027661D98788>>
[INFO]2021-06-03 12:57:28,685: create lock <lock name:elevatorMgr.lock,<unlocked _thread.RLock object owner=0 count=0 at 0x0000027661D98300>>
[INFO]2021-06-03 12:57:28,692: create lock <lock name:agvserver,<unlocked _thread.RLock object owner=0 count=0 at 0x0000027661EAF710>>
[INFO]2021-06-03 12:57:28,837: create lock <lock name:mapMgr.lock,<unlocked _thread.RLock object owner=0 count=0 at 0x000002766015C198>>
[INFO]2021-06-03 12:57:29,048: create lock <lock name:agvList.g_agvLock,<unlocked _thread.RLock object owner=0 count=0 at 0x0000027661F6FE40>>
[INFO]2021-06-03 12:57:29,051: create lock <lock name:taskList.lock,<unlocked _thread.RLock object owner=0 count=0 at 0x0000027661FB7FD0>>
[INFO]2021-06-03 12:57:29,098: charge policy 0 , fix time
[INFO]2021-06-03 12:57:29,123: create lock <lock name:agvApi.g_lock,<unlocked _thread.RLock object owner=0 count=0 at 0x000002766202D1C0>>
[INFO]2021-06-03 12:57:29,546: start load map C:\Users\comba\Desktop\KLC\knowledgeCity\agvCtrl\projects\knowledgeCity\comba-ZSC-3F_0419.smap
[DEBUG]2021-06-03 12:57:29,620: elevator thread start
[INFO]2021-06-03 12:57:29,635: load map C:\Users\comba\Desktop\KLC\knowledgeCity\agvCtrl\projects\knowledgeCity\comba-ZSC-3F_0419.smap ,used 96 ms
[INFO]2021-06-03 12:57:29,642: start load map C:\Users\comba\Desktop\KLC\knowledgeCity\agvCtrl\projects\knowledgeCity\comba-ZSC-F1-F3.smap
[INFO]2021-06-03 12:57:29,784: load map C:\Users\comba\Desktop\KLC\knowledgeCity\agvCtrl\projects\knowledgeCity\comba-ZSC-F1-F3.smap ,used 149 ms
[INFO]2021-06-03 12:57:29,792: start load map C:\Users\comba\Desktop\KLC\knowledgeCity\agvCtrl\projects\knowledgeCity\comba-ZXC-3F.smap
[INFO]2021-06-03 12:57:29,865: load map C:\Users\comba\Desktop\KLC\knowledgeCity\agvCtrl\projects\knowledgeCity\comba-ZXC-3F.smap ,used 80 ms
[INFO]2021-06-03 12:57:29,872: start load map C:\Users\comba\Desktop\KLC\knowledgeCity\agvCtrl\projects\knowledgeCity\comba-ZXC-F3.smap
[INFO]2021-06-03 12:57:29,921: load map C:\Users\comba\Desktop\KLC\knowledgeCity\agvCtrl\projects\knowledgeCity\comba-ZXC-F3.smap ,used 56 ms
[INFO]2021-06-03 12:57:29,928: start load map C:\Users\comba\Desktop\KLC\knowledgeCity\agvCtrl\projects\knowledgeCity\office.smap
[INFO]2021-06-03 12:57:29,960: load map C:\Users\comba\Desktop\KLC\knowledgeCity\agvCtrl\projects\knowledgeCity\office.smap ,used 38 ms
[INFO]2021-06-03 12:57:29,963: import agvDevice.main_agvDevice
[INFO]2021-06-03 12:57:29,964: import alarm.main_alarm
[INFO]2021-06-03 12:57:29,964: import auth.main_auth
[INFO]2021-06-03 12:57:29,971: import autoCtrl.main_akmCtrl
[CRITICAL]2021-06-03 12:57:29,983: import main_akmCtrl failed, path: autoCtrl cause a error: inconsistent use of tabs and spaces in indentation (runTasks.py, line 737)
pid=12332, ppid=9384, tid=9532
Traceback (most recent call last):
  File "run_all.py", line 39, in findModule
    __import__(m[1])
  File "C:\Users\comba\Desktop\KLC\knowledgeCity\autoCtrl\main_akmCtrl.py", line 18, in <module>
    import deviceCtrl
  File "C:\Users\comba\Desktop\KLC\knowledgeCity\autoCtrl\deviceCtrl.py", line 22, in <module>
    import runTasks
  File "C:\Users\comba\Desktop\KLC\knowledgeCity\autoCtrl\runTasks.py", line 737
    if s == 0:
             ^
TabError: inconsistent use of tabs and spaces in indentation

[CRITICAL]2021-06-03 12:57:29,985: import main_akmCtrl failed, path: autoCtrl ,cause inconsistent use of tabs and spaces in indentation (runTasks.py, line 737)
[INFO]2021-06-03 12:57:33,420: load agv file: C:\Users\comba\Desktop\KLC\knowledgeCity\agvCtrl/projects/knowledgeCity/agv.cfg
[INFO]2021-06-03 12:57:33,422: create lock <lock name:agvList.AGV01.lock,<unlocked _thread.RLock object owner=0 count=0 at 0x00000276624E4698>>
[DEBUG]2021-06-03 12:57:33,425: create aliveObj AGV01 AGV离线异常 timeout 300
[INFO]2021-06-03 12:57:33,426: AGV01 start agvList run thread
[INFO]2021-06-03 12:57:33,426: AGV01 start agvList run2 thread
[INFO]2021-06-03 12:57:33,427: create lock <lock name:agv.AGV01.lock_status,<unlocked _thread.RLock object owner=0 count=0 at 0x00000276624E4968>>
[DEBUG]2021-06-03 12:57:33,428: try connect AGV01 172.16.217.209:19204
[INFO]2021-06-03 12:57:33,429: create lock <lock name:agvList.AGVdiniu.lock,<unlocked _thread.RLock object owner=0 count=0 at 0x00000276624E4990>>
[DEBUG]2021-06-03 12:57:33,432: create aliveObj AGVdiniu AGV离线异常 timeout 300
[INFO]2021-06-03 12:57:33,433: AGVdiniu start agvList run thread
[INFO]2021-06-03 12:57:33,433: AGVdiniu start agvList run2 thread
[INFO]2021-06-03 12:57:33,433: create lock <lock name:agvList.AGVwuliao.lock,<unlocked _thread.RLock object owner=0 count=0 at 0x00000276624E4B20>>
[INFO]2021-06-03 12:57:33,433: create lock <lock name:agv.AGVdiniu.lock_status,<unlocked _thread.RLock object owner=0 count=0 at 0x00000276624E4B70>>
[DEBUG]2021-06-03 12:57:33,435: try connect AGVdiniu 172.16.217.121:19204
[DEBUG]2021-06-03 12:57:33,437: create aliveObj AGVwuliao AGV离线异常 timeout 300
[INFO]2021-06-03 12:57:33,437: AGVwuliao start agvList run thread
[INFO]2021-06-03 12:57:33,438: AGVwuliao start agvList run2 thread
[INFO]2021-06-03 12:57:33,438: create lock <lock name:agvList.AGVchache.lock,<unlocked _thread.RLock object owner=0 count=0 at 0x00000276624E4DA0>>
[INFO]2021-06-03 12:57:33,438: create lock <lock name:agv.AGVwuliao.lock_status,<unlocked _thread.RLock object owner=0 count=0 at 0x00000276624E4DF0>>
[DEBUG]2021-06-03 12:57:33,439: try connect AGVwuliao 172.16.217.211:19204
[DEBUG]2021-06-03 12:57:33,441: create aliveObj AGVchache AGV离线异常 timeout 300
[INFO]2021-06-03 12:57:33,442: AGVchache start agvList run thread
[INFO]2021-06-03 12:57:33,442: AGVchache start agvList run2 thread
[INFO]2021-06-03 12:57:33,514: create lock <lock name:agv.AGVchache.lock_status,<unlocked _thread.RLock object owner=0 count=0 at 0x00000276643D01E8>>
[INFO]2021-06-03 12:57:33,514: AGVwuliao connected 172.16.217.211 19204
[INFO]2021-06-03 12:57:33,515: AGVdiniu connected 172.16.217.121 19204
[DEBUG]2021-06-03 12:57:33,524: try connect AGVchache 172.16.217.213:19204
[INFO]2021-06-03 12:57:33,526: create lock <lock name:agv.AGVwuliao.lock_ctrl,<unlocked _thread.RLock object owner=0 count=0 at 0x00000276624E4F08>>
[INFO]2021-06-03 12:57:33,526: create lock <lock name:agv.AGVdiniu.lock_ctrl,<unlocked _thread.RLock object owner=0 count=0 at 0x00000276624E4CD8>>
[DEBUG]2021-06-03 12:57:33,527: try connect AGVwuliao 172.16.217.211:19205
[DEBUG]2021-06-03 12:57:33,528: try connect AGVdiniu 172.16.217.121:19205
[INFO]2021-06-03 12:57:33,535: AGVwuliao connected 172.16.217.211 19205
[INFO]2021-06-03 12:57:33,535: create lock <lock name:agv.AGVwuliao.lock_task,<unlocked _thread.RLock object owner=0 count=0 at 0x00000276643D0210>>
[DEBUG]2021-06-03 12:57:33,536: try connect AGVwuliao 172.16.217.211:19206
[INFO]2021-06-03 12:57:33,544: AGVdiniu connected 172.16.217.121 19205
[INFO]2021-06-03 12:57:33,545: create lock <lock name:agv.AGVdiniu.lock_task,<unlocked _thread.RLock object owner=0 count=0 at 0x00000276643D0288>>
[DEBUG]2021-06-03 12:57:33,546: try connect AGVdiniu 172.16.217.121:19206
[INFO]2021-06-03 12:57:33,568: AGVwuliao connected 172.16.217.211 19206
[INFO]2021-06-03 12:57:33,572: AGVdiniu connected 172.16.217.121 19206
[INFO]2021-06-03 12:57:33,578: create lock <lock name:agv.AGVwuliao.lock_conf,<unlocked _thread.RLock object owner=0 count=0 at 0x00000276643D02B0>>
[INFO]2021-06-03 12:57:33,587: create lock <lock name:agv.AGVdiniu.lock_conf,<unlocked _thread.RLock object owner=0 count=0 at 0x00000276643D0148>>
[DEBUG]2021-06-03 12:57:33,596: try connect AGVwuliao 172.16.217.211:19207
[DEBUG]2021-06-03 12:57:33,597: try connect AGVdiniu 172.16.217.121:19207
[INFO]2021-06-03 12:57:33,651: AGVwuliao connected 172.16.217.211 19207
[INFO]2021-06-03 12:57:33,652: AGVdiniu connected 172.16.217.121 19207
[INFO]2021-06-03 12:57:33,658: create lock <lock name:agv.AGVwuliao.lock_core,<unlocked _thread.RLock object owner=0 count=0 at 0x00000276646C5A08>>
[INFO]2021-06-03 12:57:33,658: create lock <lock name:agv.AGVdiniu.lock_core,<unlocked _thread.RLock object owner=0 count=0 at 0x00000276646C5A80>>
[DEBUG]2021-06-03 12:57:33,659: try connect AGVwuliao 172.16.217.211:19208
[DEBUG]2021-06-03 12:57:33,659: try connect AGVdiniu 172.16.217.121:19208
[INFO]2021-06-03 12:57:33,680: AGVdiniu connected 172.16.217.121 19208
[INFO]2021-06-03 12:57:33,704: create lock <lock name:agv.AGVdiniu.lock_other,<unlocked _thread.RLock object owner=0 count=0 at 0x00000276646C5FA8>>
[DEBUG]2021-06-03 12:57:33,704: try connect AGVdiniu 172.16.217.121:19210
[INFO]2021-06-03 12:57:33,755: AGVwuliao connected 172.16.217.211 19208
[INFO]2021-06-03 12:57:33,761: create lock <lock name:agv.AGVwuliao.lock_other,<unlocked _thread.RLock object owner=0 count=0 at 0x00000276646C5C60>>
[DEBUG]2021-06-03 12:57:33,762: try connect AGVwuliao 172.16.217.211:19210
[INFO]2021-06-03 12:57:33,767: AGVwuliao connected 172.16.217.211 19210
[INFO]2021-06-03 12:57:33,771: AGVdiniu connected 172.16.217.121 19210
[INFO]2021-06-03 12:57:33,800: AGVwuliao current map comba-ZXC-F3
[INFO]2021-06-03 12:57:33,851: AGVdiniu current map comba-ZXC-3F
[INFO]2021-06-03 12:57:33,860: AGVwuliao is online
[ERROR]2021-06-03 12:57:33,865: raise alarm obj=AGVwuliao, typeId=49997, desc=小车置信度小于最低阈值,当前值:0.6463
[INFO]2021-06-03 12:57:33,881: AGVdiniu is online
[ERROR]2021-06-03 12:57:43,429: connect AGV01 failed timed out
[DEBUG]2021-06-03 12:57:43,430: try connect AGV01 172.16.217.209:19204
[ERROR]2021-06-03 12:57:43,528: connect AGVchache failed timed out
[DEBUG]2021-06-03 12:57:43,532: try connect AGVchache 172.16.217.213:19204
[ERROR]2021-06-03 12:57:53,431: connect AGV01 failed timed out
[INFO]2021-06-03 12:57:53,437: AGV01 checkLink failed 172.16.217.209 19204
[WARN]2021-06-03 12:57:53,438: agvThread.AGV01[tid:7020] <lock name:agv.AGV01.lock_status,<locked _thread.RLock object owner=7020 count=1 at 0x00000276624E4968>> ,hold 20010 ms
[INFO]2021-06-03 12:57:53,439: name=agvThread.AGV01, pid=12332, tid=7020
[01] File "C:/Users/comba/AppData/Local/Programs/Python/Python37/lib/threading.py", line 865, in run() 
[02] File "C:/Users/comba/Desktop/KLC/knowledgeCity/agvCtrl/agvList.py", line 582, in run() 
[03] File "../driver/seerAgv/agvCtrl.py", line 36, in checkLink() 
[04] File "../driver/seerAgv/agvApi.py", line 185, in checkLink() 
[05] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/lock.py", line 102, in release() 
[06] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/enhance.py", line 268, in getTrace() 
[07] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/enhance.py", line 248, in getThreadStack()
[ERROR]2021-06-03 12:57:53,535: connect AGVchache failed timed out
[INFO]2021-06-03 12:57:53,539: AGVchache checkLink failed 172.16.217.213 19204
[WARN]2021-06-03 12:57:53,542: agvThread.AGVchache[tid:11432] <lock name:agv.AGVchache.lock_status,<locked _thread.RLock object owner=11432 count=1 at 0x00000276643D01E8>> ,hold 20018 ms
[INFO]2021-06-03 12:57:53,546: name=agvThread.AGVchache, pid=12332, tid=11432
[01] File "C:/Users/comba/AppData/Local/Programs/Python/Python37/lib/threading.py", line 865, in run() 
[02] File "C:/Users/comba/Desktop/KLC/knowledgeCity/agvCtrl/agvList.py", line 582, in run() 
[03] File "../driver/seerAgv/agvCtrl.py", line 36, in checkLink() 
[04] File "../driver/seerAgv/agvApi.py", line 185, in checkLink() 
[05] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/lock.py", line 102, in release() 
[06] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/enhance.py", line 268, in getTrace() 
[07] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/enhance.py", line 248, in getThreadStack()
[DEBUG]2021-06-03 12:57:55,442: try connect AGV01 172.16.217.209:19204
[DEBUG]2021-06-03 12:57:55,554: try connect AGVchache 172.16.217.213:19204
[ERROR]2021-06-03 12:58:05,447: connect AGV01 failed timed out
[INFO]2021-06-03 12:58:05,454: AGV01 checkLink failed 172.16.217.209 19204
[WARN]2021-06-03 12:58:05,457: agvThread.AGV01[tid:7020] <lock name:agv.AGV01.lock_status,<locked _thread.RLock object owner=7020 count=1 at 0x00000276624E4968>> ,hold 10015 ms
[INFO]2021-06-03 12:58:05,462: name=agvThread.AGV01, pid=12332, tid=7020
[01] File "C:/Users/comba/AppData/Local/Programs/Python/Python37/lib/threading.py", line 865, in run() 
[02] File "C:/Users/comba/Desktop/KLC/knowledgeCity/agvCtrl/agvList.py", line 582, in run() 
[03] File "../driver/seerAgv/agvCtrl.py", line 36, in checkLink() 
[04] File "../driver/seerAgv/agvApi.py", line 185, in checkLink() 
[05] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/lock.py", line 102, in release() 
[06] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/enhance.py", line 268, in getTrace() 
[07] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/enhance.py", line 248, in getThreadStack()
[ERROR]2021-06-03 12:58:05,558: connect AGVchache failed timed out
[INFO]2021-06-03 12:58:05,562: AGVchache checkLink failed 172.16.217.213 19204
[WARN]2021-06-03 12:58:05,565: agvThread.AGVchache[tid:11432] <lock name:agv.AGVchache.lock_status,<locked _thread.RLock object owner=11432 count=1 at 0x00000276643D01E8>> ,hold 10011 ms
[INFO]2021-06-03 12:58:05,569: name=agvThread.AGVchache, pid=12332, tid=11432
[01] File "C:/Users/comba/AppData/Local/Programs/Python/Python37/lib/threading.py", line 865, in run() 
[02] File "C:/Users/comba/Desktop/KLC/knowledgeCity/agvCtrl/agvList.py", line 582, in run() 
[03] File "../driver/seerAgv/agvCtrl.py", line 36, in checkLink() 
[04] File "../driver/seerAgv/agvApi.py", line 185, in checkLink() 
[05] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/lock.py", line 102, in release() 
[06] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/enhance.py", line 268, in getTrace() 
[07] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/enhance.py", line 248, in getThreadStack()
[DEBUG]2021-06-03 12:58:07,468: try connect AGV01 172.16.217.209:19204
[DEBUG]2021-06-03 12:58:07,575: try connect AGVchache 172.16.217.213:19204
[ERROR]2021-06-03 12:58:17,473: connect AGV01 failed timed out
[INFO]2021-06-03 12:58:17,477: AGV01 checkLink failed 172.16.217.209 19204
[WARN]2021-06-03 12:58:17,480: agvThread.AGV01[tid:7020] <lock name:agv.AGV01.lock_status,<locked _thread.RLock object owner=7020 count=1 at 0x00000276624E4968>> ,hold 10012 ms
[INFO]2021-06-03 12:58:17,484: name=agvThread.AGV01, pid=12332, tid=7020
[01] File "C:/Users/comba/AppData/Local/Programs/Python/Python37/lib/threading.py", line 865, in run() 
[02] File "C:/Users/comba/Desktop/KLC/knowledgeCity/agvCtrl/agvList.py", line 582, in run() 
[03] File "../driver/seerAgv/agvCtrl.py", line 36, in checkLink() 
[04] File "../driver/seerAgv/agvApi.py", line 185, in checkLink() 
[05] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/lock.py", line 102, in release() 
[06] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/enhance.py", line 268, in getTrace() 
[07] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/enhance.py", line 248, in getThreadStack()
[ERROR]2021-06-03 12:58:17,581: connect AGVchache failed timed out
[INFO]2021-06-03 12:58:17,581: AGVchache checkLink failed 172.16.217.213 19204
[WARN]2021-06-03 12:58:17,585: agvThread.AGVchache[tid:11432] <lock name:agv.AGVchache.lock_status,<locked _thread.RLock object owner=11432 count=1 at 0x00000276643D01E8>> ,hold 10010 ms
[INFO]2021-06-03 12:58:17,586: name=agvThread.AGVchache, pid=12332, tid=11432
[01] File "C:/Users/comba/AppData/Local/Programs/Python/Python37/lib/threading.py", line 865, in run() 
[02] File "C:/Users/comba/Desktop/KLC/knowledgeCity/agvCtrl/agvList.py", line 582, in run() 
[03] File "../driver/seerAgv/agvCtrl.py", line 36, in checkLink() 
[04] File "../driver/seerAgv/agvApi.py", line 185, in checkLink() 
[05] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/lock.py", line 102, in release() 
[06] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/enhance.py", line 268, in getTrace() 
[07] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/enhance.py", line 248, in getThreadStack()
[DEBUG]2021-06-03 12:58:19,493: try connect AGV01 172.16.217.209:19204
[DEBUG]2021-06-03 12:58:19,588: try connect AGVchache 172.16.217.213:19204
[ERROR]2021-06-03 12:58:29,498: connect AGV01 failed timed out
[INFO]2021-06-03 12:58:29,500: AGV01 checkLink failed 172.16.217.209 19204
[WARN]2021-06-03 12:58:29,501: agvThread.AGV01[tid:7020] <lock name:agv.AGV01.lock_status,<locked _thread.RLock object owner=7020 count=1 at 0x00000276624E4968>> ,hold 10008 ms
[INFO]2021-06-03 12:58:29,502: name=agvThread.AGV01, pid=12332, tid=7020
[01] File "C:/Users/comba/AppData/Local/Programs/Python/Python37/lib/threading.py", line 865, in run() 
[02] File "C:/Users/comba/Desktop/KLC/knowledgeCity/agvCtrl/agvList.py", line 582, in run() 
[03] File "../driver/seerAgv/agvCtrl.py", line 36, in checkLink() 
[04] File "../driver/seerAgv/agvApi.py", line 185, in checkLink() 
[05] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/lock.py", line 102, in release() 
[06] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/enhance.py", line 268, in getTrace() 
[07] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/enhance.py", line 248, in getThreadStack()
[ERROR]2021-06-03 12:58:29,594: connect AGVchache failed timed out
[INFO]2021-06-03 12:58:29,594: AGVchache checkLink failed 172.16.217.213 19204
[WARN]2021-06-03 12:58:29,595: agvThread.AGVchache[tid:11432] <lock name:agv.AGVchache.lock_status,<locked _thread.RLock object owner=11432 count=1 at 0x00000276643D01E8>> ,hold 10007 ms
[INFO]2021-06-03 12:58:29,606: name=agvThread.AGVchache, pid=12332, tid=11432
[01] File "C:/Users/comba/AppData/Local/Programs/Python/Python37/lib/threading.py", line 865, in run() 
[02] File "C:/Users/comba/Desktop/KLC/knowledgeCity/agvCtrl/agvList.py", line 582, in run() 
[03] File "../driver/seerAgv/agvCtrl.py", line 36, in checkLink() 
[04] File "../driver/seerAgv/agvApi.py", line 185, in checkLink() 
[05] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/lock.py", line 102, in release() 
[06] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/enhance.py", line 268, in getTrace() 
[07] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/enhance.py", line 248, in getThreadStack()
[DEBUG]2021-06-03 12:58:31,504: try connect AGV01 172.16.217.209:19204
[DEBUG]2021-06-03 12:58:31,608: try connect AGVchache 172.16.217.213:19204
[ERROR]2021-06-03 12:58:41,506: connect AGV01 failed timed out
[INFO]2021-06-03 12:58:41,508: AGV01 checkLink failed 172.16.217.209 19204
[WARN]2021-06-03 12:58:41,509: agvThread.AGV01[tid:7020] <lock name:agv.AGV01.lock_status,<locked _thread.RLock object owner=7020 count=1 at 0x00000276624E4968>> ,hold 10005 ms
[INFO]2021-06-03 12:58:41,511: name=agvThread.AGV01, pid=12332, tid=7020
[01] File "C:/Users/comba/AppData/Local/Programs/Python/Python37/lib/threading.py", line 865, in run() 
[02] File "C:/Users/comba/Desktop/KLC/knowledgeCity/agvCtrl/agvList.py", line 582, in run() 
[03] File "../driver/seerAgv/agvCtrl.py", line 36, in checkLink() 
[04] File "../driver/seerAgv/agvApi.py", line 185, in checkLink() 
[05] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/lock.py", line 102, in release() 
[06] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/enhance.py", line 268, in getTrace() 
[07] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/enhance.py", line 248, in getThreadStack()
[ERROR]2021-06-03 12:58:41,623: connect AGVchache failed timed out
[INFO]2021-06-03 12:58:41,624: AGVchache checkLink failed 172.16.217.213 19204
[WARN]2021-06-03 12:58:41,625: agvThread.AGVchache[tid:11432] <lock name:agv.AGVchache.lock_status,<locked _thread.RLock object owner=11432 count=1 at 0x00000276643D01E8>> ,hold 10017 ms
[INFO]2021-06-03 12:58:41,626: name=agvThread.AGVchache, pid=12332, tid=11432
[01] File "C:/Users/comba/AppData/Local/Programs/Python/Python37/lib/threading.py", line 865, in run() 
[02] File "C:/Users/comba/Desktop/KLC/knowledgeCity/agvCtrl/agvList.py", line 582, in run() 
[03] File "../driver/seerAgv/agvCtrl.py", line 36, in checkLink() 
[04] File "../driver/seerAgv/agvApi.py", line 185, in checkLink() 
[05] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/lock.py", line 102, in release() 
[06] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/enhance.py", line 268, in getTrace() 
[07] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/enhance.py", line 248, in getThreadStack()
[DEBUG]2021-06-03 12:58:43,513: try connect AGV01 172.16.217.209:19204
[DEBUG]2021-06-03 12:58:43,628: try connect AGVchache 172.16.217.213:19204
[ERROR]2021-06-03 12:58:53,518: connect AGV01 failed timed out
[INFO]2021-06-03 12:58:53,522: AGV01 checkLink failed 172.16.217.209 19204
[WARN]2021-06-03 12:58:53,525: agvThread.AGV01[tid:7020] <lock name:agv.AGV01.lock_status,<locked _thread.RLock object owner=7020 count=1 at 0x00000276624E4968>> ,hold 10012 ms
[INFO]2021-06-03 12:58:53,529: name=agvThread.AGV01, pid=12332, tid=7020
[01] File "C:/Users/comba/AppData/Local/Programs/Python/Python37/lib/threading.py", line 865, in run() 
[02] File "C:/Users/comba/Desktop/KLC/knowledgeCity/agvCtrl/agvList.py", line 582, in run() 
[03] File "../driver/seerAgv/agvCtrl.py", line 36, in checkLink() 
[04] File "../driver/seerAgv/agvApi.py", line 185, in checkLink() 
[05] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/lock.py", line 102, in release() 
[06] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/enhance.py", line 268, in getTrace() 
[07] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/enhance.py", line 248, in getThreadStack()
[ERROR]2021-06-03 12:58:53,629: connect AGVchache failed timed out
[INFO]2021-06-03 12:58:53,633: AGVchache checkLink failed 172.16.217.213 19204
[WARN]2021-06-03 12:58:53,634: agvThread.AGVchache[tid:11432] <lock name:agv.AGVchache.lock_status,<locked _thread.RLock object owner=11432 count=1 at 0x00000276643D01E8>> ,hold 10006 ms
[INFO]2021-06-03 12:58:53,635: name=agvThread.AGVchache, pid=12332, tid=11432
[01] File "C:/Users/comba/AppData/Local/Programs/Python/Python37/lib/threading.py", line 865, in run() 
[02] File "C:/Users/comba/Desktop/KLC/knowledgeCity/agvCtrl/agvList.py", line 582, in run() 
[03] File "../driver/seerAgv/agvCtrl.py", line 36, in checkLink() 
[04] File "../driver/seerAgv/agvApi.py", line 185, in checkLink() 
[05] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/lock.py", line 102, in release() 
[06] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/enhance.py", line 268, in getTrace() 
[07] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/enhance.py", line 248, in getThreadStack()
[DEBUG]2021-06-03 12:58:55,535: try connect AGV01 172.16.217.209:19204
[DEBUG]2021-06-03 12:58:55,637: try connect AGVchache 172.16.217.213:19204
[ERROR]2021-06-03 12:59:05,540: connect AGV01 failed timed out
[INFO]2021-06-03 12:59:05,544: AGV01 checkLink failed 172.16.217.209 19204
[WARN]2021-06-03 12:59:05,547: agvThread.AGV01[tid:7020] <lock name:agv.AGV01.lock_status,<locked _thread.RLock object owner=7020 count=1 at 0x00000276624E4968>> ,hold 10012 ms
[INFO]2021-06-03 12:59:05,551: name=agvThread.AGV01, pid=12332, tid=7020
[01] File "C:/Users/comba/AppData/Local/Programs/Python/Python37/lib/threading.py", line 865, in run() 
[02] File "C:/Users/comba/Desktop/KLC/knowledgeCity/agvCtrl/agvList.py", line 582, in run() 
[03] File "../driver/seerAgv/agvCtrl.py", line 36, in checkLink() 
[04] File "../driver/seerAgv/agvApi.py", line 185, in checkLink() 
[05] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/lock.py", line 102, in release() 
[06] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/enhance.py", line 268, in getTrace() 
[07] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/enhance.py", line 248, in getThreadStack()
[ERROR]2021-06-03 12:59:05,638: connect AGVchache failed timed out
[INFO]2021-06-03 12:59:05,639: AGVchache checkLink failed 172.16.217.213 19204
[WARN]2021-06-03 12:59:05,640: agvThread.AGVchache[tid:11432] <lock name:agv.AGVchache.lock_status,<locked _thread.RLock object owner=11432 count=1 at 0x00000276643D01E8>> ,hold 10003 ms
[INFO]2021-06-03 12:59:05,641: name=agvThread.AGVchache, pid=12332, tid=11432
[01] File "C:/Users/comba/AppData/Local/Programs/Python/Python37/lib/threading.py", line 865, in run() 
[02] File "C:/Users/comba/Desktop/KLC/knowledgeCity/agvCtrl/agvList.py", line 582, in run() 
[03] File "../driver/seerAgv/agvCtrl.py", line 36, in checkLink() 
[04] File "../driver/seerAgv/agvApi.py", line 185, in checkLink() 
[05] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/lock.py", line 102, in release() 
[06] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/enhance.py", line 268, in getTrace() 
[07] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/enhance.py", line 248, in getThreadStack()
[DEBUG]2021-06-03 12:59:07,559: try connect AGV01 172.16.217.209:19204
[DEBUG]2021-06-03 12:59:07,643: try connect AGVchache 172.16.217.213:19204
