[CRITICAL]2020-04-26 11:16:46,177: update task error: cause a error: 'NoneType' object has no attribute 'setBackground'
pid=2148, ppid=9592, tid=7860
Traceback (most recent call last):
  File "E:/python_work/akm/akmCtrl/taskUI.py", line 183, in autoUpdateTask
    self.updateTaskBydb()
  File "E:/python_work/akm/akmCtrl/taskUI.py", line 170, in updateTaskBydb
    self.updateTask(tasks[i], index)
  File "E:/python_work/akm/akmCtrl/taskUI.py", line 119, in updateTask
    set(i, task["name"])
  File "E:/python_work/akm/akmCtrl/taskUI.py", line 112, in set
    setItemColor(rowIndex,col,bgColor = resultColor)
  File "E:/python_work/akm/akmCtrl/taskUI.py", line 87, in setItemColor
    self.table.itemAt(rowIndex,cellIndex).setBackground(PyQt5.QtGui.QBrush(PyQt5.QtGui.QColor(bgColor)))
AttributeError: 'NoneType' object has no attribute 'setBackground'

[CRITICAL]2020-04-26 11:17:13,139: update task error: cause a error: 'NoneType' object has no attribute 'setBackground'
pid=2148, ppid=9592, tid=7860
Traceback (most recent call last):
  File "E:/python_work/akm/akmCtrl/taskUI.py", line 183, in autoUpdateTask
    self.updateTaskBydb()
  File "E:/python_work/akm/akmCtrl/taskUI.py", line 170, in updateTaskBydb
    self.updateTask(tasks[i], index)
  File "E:/python_work/akm/akmCtrl/taskUI.py", line 119, in updateTask
    set(i, task["name"])
  File "E:/python_work/akm/akmCtrl/taskUI.py", line 112, in set
    setItemColor(rowIndex,col,bgColor = resultColor)
  File "E:/python_work/akm/akmCtrl/taskUI.py", line 87, in setItemColor
    self.table.itemAt(rowIndex,cellIndex).setBackground(PyQt5.QtGui.QBrush(PyQt5.QtGui.QColor(bgColor)))
AttributeError: 'NoneType' object has no attribute 'setBackground'

